version: '3.7'

services:

  web:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile_dev
    hostname: 0.0.0.0
    command: npm start
    container_name: sprint-web-dev
    image: sprint-web/dev
    volumes:
      - ./src:/home/sprint-web/src
    ports:
      - 4500:4500
