apiVersion: apps/v1
kind: Deployment
metadata:
  name: [app-name]
  namespace: tms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: [app-name]
  template:
    metadata:
      labels:
        app: [app-name]
    spec:
      containers:
      - name: [app-name]
        image: cgtmsarcdev.azurecr.io/[registry-name]:[tag]
        ports:
        - containerPort: 80
          protocol: TCP
      imagePullSecrets:
        - name: cgtmsarcdev-azurecr-secret