apiVersion: v1
kind: Service
metadata:
  name: tms-angular-front
  namespace: tms
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 31001
  selector:
    app: tms-angular-front