apiVersion: v1
kind: Service
metadata:
  name: tms-master-data-service
  namespace: tms
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30101
  selector:
    app: tms-master-data-service